### ISSUE TITLE
If not fully configured plugin breaks activity edit page

### ISSUE THREAD

**Issue by mhughes2k** [turnitin/moodle-plagiarism_turnitin#110]
If the turnitin module is not fully configured it causes the activity edit settings page to completely fail.
![image](https://cloud.githubusercontent.com/assets/694841/13741545/d0b98032-e9ce-11e5-94b4-e3732770446f.png)

Whilst it is important that things are configured, it is pretty bad that this happens. We have valid cases where we do *not* want Turnitin configured and talking to the TII service (e.g. test servers / clones) so this prevents the core moodle functionality working.

If Turnitin is not configured please can it just assume it is completely disabled and not offer any TII settings rather than breaking the whole page.

**Comment by mkpelletier** [comment]
I also get this when configuring a newly restored course.  That is, when setting up a new course > edit assignment > error returns on the first load only.  Subsequent edits of the assignment work fine, as it would appear the course only gets created (in turnitin) when the assignment is opened for the first time.  

Is this the same error as reported above or different?

![error](https://cloud.githubusercontent.com/assets/4638072/13743018/ffcccdd4-e9e7-11e5-9f25-94a7e8864945.jpg)

**Comment by jmcgettrick** [comment]
Hi @mhughes2k - we'll get that looked at.

Hi @mkpelletier - I think you're error could be because just after the class is created the plugin is trying to enrol all admins and instructors on it. Is it possible that you have an admin who doesn't have a valid email address?

**Comment by mkpelletier** [comment]
Hello John,

The course is being set up from a backup, so there are no enrolments on the
course.   We only add enrolments after the course has been configured.  My
admin account uses an email address which I use daily.

Sent from my phone
pardon brevity and typos

Hi @mhughes2k <https://github.com/mhughes2k> - we'll get that looked at.

Hi @mkpelletier <https://github.com/mkpelletier> - I think you're error
could be because just after the class is created the plugin is trying to
enrol all admins and instructors on it. Is it possible that you have an
admin who doesn't have a valid email address?

—
Reply to this email directly or view it on GitHub
<https://github.com/turnitin/moodle-plagiarism_turnitin/issues/110#issuecomment-196486011>
.

**Comment by jmcgettrick** [comment]
Can you look in your API logs and see what the request is when that error is occuring?

**Comment by jmcgettrick** [comment]
Hi @mhughes2k, this has been fixed in latest release 2016072601
