### ISSUE TITLE
Enable TII for assignment with TII defaults after restoring a non-TII assignment.

### ISSUE THREAD

**Issue by roperto** [turnitin/moodle-plagiarism_turnitin#228]
This is a suggestion for an enhancement.

When we import an assignment from a system that did not have TII installed (could be from another site or an older assignment) into a Moodle with TII installed, the plugin does not get the default settings set.

I believe in this situation, in the restore process, turn it it should configure that "new" assignment using the site defaults. This is basically the same as editing the assignment after the restore and saving it without changes (it will apply the defaults).

As an extra benefit, some settings could be locked and doing that will ensure consistent settings.

**Comment by roperto** [comment]
I did some research on the restore process, the only function called in `restore_plagiarism_turnitin_plugin.class.php` when the assignment being restored does not have the TII settings is `define_module_plugin_structure()`, which is not the place where we should enforce the TII settings for the restored assignment.

One solution would be to add a cron task to create missing settings, or to create them when it is needed for the first time.

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
