### ISSUE TITLE
Feature request; more activity completion options for Turnitin assingment

### ISSUE THREAD

**Issue by Jarvil** [turnitin/moodle-plagiarism_turnitin#270]
Hello,

I would like to see more activity completion options for Turnitin assingment like in the normal assignment-activity. So it could be

"Student must submit to this activity to complete it"

**Comment by Jarvil** [comment]
Hello,

Any progress on this?

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
