### ISSUE TITLE
Launch Rubric Manager and Duplicate an item throws an error

### ISSUE THREAD

**Issue by whymiss** [turnitin/moodle-plagiarism_turnitin#301]
When accessing the Launch Rubric manager from within the Moodle Assignment settings we get errors when duplicating rubrics or grading forms. Initially if a form or rubric is chosen for duplication the duplicated item appears. However when trying to edit the duplicated item the text will not change and updates will not save... if they do appear to have been changed when the Save button is hit an error occurs stating Save Error The request failed because the request was invalid or incomplete.
![rubricmanager](https://user-images.githubusercontent.com/4484052/38065862-dad114ca-3361-11e8-9391-c1a5d0c2b51f.PNG)

our workaround is to access the rubric manager via the full Feedback Studio interface.
Moodle 3.4.1
Turnitin PP 2.7+ 2018011602

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
