### ISSUE TITLE
Teachers Edit Assignments - Not Sent to TII

### ISSUE THREAD

**Issue by jezhops** [turnitin/moodle-plagiarism_turnitin#306]
In Moodle there is a capablility editothersubmission which allows tutors to upload assignments on behalf of a student:

https://docs.moodle.org/32/en/Capabilities/mod/assign:editothersubmission

When this capability is enabled for teachers they see an "edit assignment" option in the grading area as shown in step 3 of the screen shot below:

![edit-submission](https://user-images.githubusercontent.com/28052145/39527744-22ab54f4-4e1a-11e8-9681-3d471f80a2c0.JPG)

When a tutor does this the assignment is not sent to TII by the plagiarism plugin which it should be.

The kind of use case we see around this is a student has problems uploading to Moodle before the deadline and emails a copy of the assignment to the tutor who can then upload it on their behalf. As such, we need to see the plagiarism report for the assignment as though it had actually been uploaded byu the student.

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
