### ISSUE TITLE
Improve the error table

### ISSUE THREAD

**Issue by mhughes2k** [turnitin/moodle-plagiarism_turnitin#378]
It would be nice if the error table could be improved. We have seen a large number of specific errors being returned but we cannot filter them to deal with just them.

When other errors are there or files have been deleted it can disrupt a resubmission action, so it would be good to be able to suppress the ones we're definitely not going to do anything with.

This would also apply in cases where the error is the student submitting the wrong file type or it not containing valid text. Whilst these are "errors", they're not fixable until the student changes them, so we have no need to see them!

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
