### ISSUE TITLE
Don't output  a check box on the errors table when file has been deleted

### ISSUE THREAD

**Issue by mhughes2k** [turnitin/moodle-plagiarism_turnitin#379]
When a file has been deleted it's not possible to resubmit, so it shouldn't have a checkbox to select it.

Equally you can't bulk delete items that have been selected, so removing the check box doesn't break bulk delete actions.

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
