### ISSUE TITLE
Requeuing submission creates fake log entries

### ISSUE THREAD

**Issue by micaherne** [turnitin/moodle-plagiarism_turnitin#387]
When using the errors page to resend files to Turnitin, a new log entry is created showing that the student resubmitted their actual assignment. This is misleading and should not happen.

An example of why this is a problem is investigation of student appeals. Each year a fairly high number of students launch an appeal against their grade for a class, and these often include assertions about the student's submission to Moodle. We are required to supply log data to the people investigating these appeals, and if this data is inaccurate it could easily lead to these appeals being falsely rejected (or upheld).

I appreciate that faking the upload event is the easiest way to requeue the submission, and probably worked well with the old events API before the event and logging systems were combined, but it's not reasonable behaviour for a plugin to do that now.

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
