### ISSUE TITLE
Check capabilities on module context

### ISSUE THREAD

**Issue by moodleulpgc** [turnitin/moodle-plagiarism_turnitin#417]
Hi:
Turnitin plagiarism plugin is used inside an assign or forum module instance. However the capabilities, plagiarism/turnitin:enable, plagiarism/turnitin:viewfullreport,  are defined & checked at course context. This is NOT standard behaviour in moodle. 

There is nothing avoiding checking the capabilities in the module context. Than module is always known to the plugin, in fact, cmid is stored in plugin tables.

Checking within context_module is expected and allows a more flexible configuration in complex setups.

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
