### ISSUE TITLE
Access controlled link files not submitting to turnitin

### ISSUE THREAD

**Issue by danmarsden** [turnitin/moodle-plagiarism_turnitin#423]
Just had this reported to us but haven't looked at it closely - just wondering if you were aware of it?

Moodle has the ability for students to select "Access controlled links" assignments files via onedrive or Google Drive.
eg:
https://docs.moodle.org/en/OneDrive_repository#Access_controlled_links

When this is done, it appears that the file is not collected correctly and sent to Turnitin 

They are using a slightly older release of this plugin (2018102901) - I couldn't see anything in the changelog related to this, but I wondered if the team/group submission fixes that have been made since then might be related - I'm going to update the site with the latest code but thought I'd ask here in case you've seen it before?

**Comment by kinnectus** [comment]
@danmarsden , did you get an answer to this?

Obviously your issue is ~2yrs old, however we cannot find anything that suggests TurnItIn plugin for Moodle supports access controlled links. It is something we are very interested in, as an institute, as it will be hugely effective for student assignments and reduce the storage required to keep the sheer volume of submissions we receive per annum.

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
