### ISSUE TITLE
Originality reports for anonymous Moodle not anonymous

### ISSUE THREAD

**Issue by thepurpleblob** [turnitin/moodle-plagiarism_turnitin#425]
To reproduce
- Create a new Assignment (as a teacher) and set it for blind marking / anonymous with TII enabled
- Get a student to submit something and wait for a score to be returned
- Click the TII score link. 

The student's name is shown at the top of the page. This is a major block for the plugin.
<img width="516" alt="Screenshot 2019-04-25 at 11 20 15" src="https://user-images.githubusercontent.com/664139/56729068-36701000-674c-11e9-91dc-6c982add06e8.png">

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
