### ISSUE TITLE
Trigger an event when score is returned

### ISSUE THREAD

**Issue by thepurpleblob** [turnitin/moodle-plagiarism_turnitin#426]
It would be really useful if the plugin triggered an event when it detected a new score had been returned. 

This would allow us to trap the event and notify students.

It also, of course, creates a useful log entry.

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.

**Comment by mwillis11** [comment]
Can we please reopen this @carl-hostrander ? It exists in Moodle 4.X installations. It is massive issue, as other plugins that do things based on submissions being graded are not fired because this plugin is not doing the right thing regarding Moodle's assessment API. 

Also need to reopen #496 on the same premise. 

Cheers.
