### ISSUE TITLE
Icon issue: The icon that looks like a sheet of paper with a red x is unclear.

### ISSUE THREAD

**Issue by zaddok** [turnitin/moodle-plagiarism_turnitin#441]
Although it is unclear in the sense that it is literally fuzzy on my MacBook. The real issue here is that it is not clear what this icon means. There is no text or mouseover text that explains what is going on. Searching for "icon with a red x" in the Turnitin support documentation doesn't turn up anything useful.

Suggest that this icon is altered, or text is included that clarifies the meaning of the icon.

**Comment by Kisa-chan** [comment]
I'm not sure if this is the same case, but we have an issue with the same icon because it seems to be for closing the error message but it actually won't close it. 
This happens when a student uploads a document in the forum, like shown below:

![image](https://github.com/turnitin/moodle-plagiarism_turnitin/assets/8128866/cdb9a6a5-e805-4e6c-9d90-d4b8620e7726)

The student clicks the x icon but nothing happens, so we want to know if that is the correct behavior or maybe something is not working in our site.

Thank you a lot in advance for your answer

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
