### ISSUE TITLE
Exclude Small Matches setting locked on admin site, but users can edit

### ISSUE THREAD

**Issue by ghost** [turnitin/moodle-plagiarism_turnitin#444]
Hello, I have the setting ' Exclude Small Matches ' set to Percent and the value to 1%. I also have set the setting as 'Locked' on Admin site (Dashboard > Site administration > Plugins > Plagiarism > Turnitin plagiarism plugin).

The expected behavior would be that teachers will not be able to change the value from the assignment settings page but currently this is not happening. Lecturers can go to the assignment settings (with role teacher) and change the value.

Am not sure if this is the correct behavior or a bug.

Moodle Version
2018051701.04;
'3.5.1+ (Build: 20180727)'; 

Plugin version
plagiarism_turnitin - 2019050201
mod_turnitintooltwo - 2019050101

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
