### ISSUE TITLE
Workshop displays error for previously failed submissions

### ISSUE THREAD

**Issue by mkpelletier** [turnitin/moodle-plagiarism_turnitin#457]
In the workshop module, if a student previously submitted an assignment which failed to process in turnitin, any subsequent successful submission still has the "Resubmit to Turnitin" above.  
<img width="275" alt="Screenshot 2019-07-02 at 08 48 58" src="https://user-images.githubusercontent.com/4638072/60490271-81efee80-9ca6-11e9-9459-d83387763043.png">

The entry with this externalid is listed as successful in mdl_plagiarism_turnitin_files, but the previous submission shows an error.
<img width="789" alt="Screenshot 2019-07-02 at 08 52 26" src="https://user-images.githubusercontent.com/4638072/60490494-ec089380-9ca6-11e9-9cb5-992a39977dbb.png">

Moodle version 3.5.3+
Plagiarism Plugin Version: 2019062501

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
