### ISSUE TITLE
Feature request: Analytics indicator

### ISSUE THREAD

**Issue by danmarsden** [turnitin/moodle-plagiarism_turnitin#474]
Just had this request from one of our clients so thought I'd add it here to hopefully gauge how popular it might be..

Moodle's Analytics API allows plugins to provide their own indicators. It would be really nice to see an indicator for turnitin similarity scores - could be an interesting metric to use when trying to identify students that might be at risk!

More info on the Analytics api is here:
https://docs.moodle.org/dev/Analytics_API#Indicator

**Comment by jmcgettrick** [comment]
Thanks Dan, we'll take a look

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
