### ISSUE TITLE
mdb->get_record() found more than one record!

### ISSUE THREAD

**Issue by ghost** [turnitin/moodle-plagiarism_turnitin#476]
Hello,

I get the following error when running the cron, does anyone know how to fix it?

```
++ Error: mdb->get_record() found more than one record! ++
* line 1583 of /lib/dml/moodle_database.php: call to debugging()
* line 1543 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()
* line 1522 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
* line 2015 of /plagiarism/turnitin/lib.php: call to moodle_database->get_record()
* line 2771 of /plagiarism/turnitin/lib.php: call to plagiarism_plugin_turnitin->cron_update_scores()
* line 44 of /plagiarism/turnitin/classes/task/update_reports.php: call to plagiarism_turnitin_update_reports()
* line 189 of /lib/cronlib.php: call to plagiarism_turnitin\task\update_reports->execute()
* line 114 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
* line 73 of /lib/cronlib.php: call to cron_run_scheduled_tasks()
* line 61 of /admin/cli/cron.php: call to cron_run()

```

Moodle version: 3.7.1+ (Build: 20190809)
mod_turnitintooltwo: 2019070201
plagiarism_turnitin: 2019062501

**Comment by agrowe** [comment]
I have seen this issue as well where there are duplicate externalids and multiple rows per student submission. The `get_record()` function will return this result as it only expects there to be 1 record returned.

To find the externalids that may be causing issues, you can run

```
SELECT externalid
FROM mdl_plagiarism_turnitin_files
WHERE externalid IS NOT NULL
GROUP BY externalid
HAVING COUNT(*) > 1
```

Then get the rows with duplicates. The rows I found to the problem had a statuscode of success but a similarityscore of null.

```
SELECT *
FROM mdl_plagiarism_turnitin_files
WHERE externalid IN (
    SELECT externalid
    FROM mdl_plagiarism_turnitin_files
    WHERE externalid IS NOT NULL
    GROUP BY externalid
    HAVING COUNT(*) > 1
)
ORDER BY externalid ASC, id ASC
```

Once you have the duplicate rows, delete duplicates but leave the original (lowest id) that should have a statuscode of success and a valid similarityscore.

There still needs to be an upstream fix though so that there can't be duplicate rows added in the first place, or extra validation around the `get_record()` statement.

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
