### ISSUE TITLE
Issues with Settings Implementation!

### ISSUE THREAD

**Issue by mhughes2k** [turnitin/moodle-plagiarism_turnitin#478]
Aside from the fact that settings.php is wildly not in the style of a normal Moodle settings page, what is going on with this function from lib.php:
```
/**
     * Set a config value for the admin settings.
     */
    public static function plagiarism_set_config($data, $property) {
        // Scenario when performing the upgrade script to copy settings from V2 to PP.
        if (strpos($property, 'plagiarism_turnitin') === false) {
            $field = "plagiarism_turnitin_".$property;
        } else {
            $field = $property;
        }

        if (isset($data->$property)) {
            set_config($field, $data->$property, 'plagiarism');
        }
    }
```

Aside from the fact that the field name ($field) is pseudo-namespaced by concatenating "plagiarism_turnitin_" with the *actual* setting, the field name & value is then stored in the "plagiarism" plugin, which *doesn't* exist as a thing.
 
It should be going into it's *own" plugin collection in the set_config() call so say for the
plagiarism_turnitin_accountid property (which really should just be "turnitin_accountid"):

```
set_config("turnitin_accountid", $data->$property, "plagiarism_turnitin")
```

Why is this an issue? We clone servers from live to test, and when we do that we have scripts that unhook the test instance from live, typically by doing something like `DELETE FROM mdl_config_plugins WHERE plugin = 'turnitintooltwo';`

With the plagiarism module it would be `DELETE FROM mdl_config_plugins WHERE plugin = 'plagiarism';` which would wipe anything else that (might) happen to be in that section of the config_plugins table....

This use of the `plagiarism` "namespace" is throughout this plugin and it breaks the isolation that should exist.

**Comment by dwinn** [comment]
Hi @micaherne,

This method exists because we recently split the Turnitin Plagiarism Plugin from Moodle Direct V2. Previously PP relied on a lot of code within the V2 plugin and you needed both installed, but now they are independent of each other.

To avoid a situation whereby users upgrading to the latest PP would suddenly find the plugin no longer configured we copied the config PP relied on in V2 to PP. That's what this method is doing.

I can see your point however that the namespace of just `plagiarism` isn't great - the reason we used that when migrating the config is because PP already used it for a few of its config and had been for many years - so we went with that for consistently. `plagiarism_turnitin` does sound like a better namespace to use however, and it is something we will discuss. To change it we would have to write another method like the above to migrate the config from `plagiarism` to `plagiarism_turnitin` to again avoid having the plugin unconfigured after an upgrade.

**Comment by mhughes2k** [comment]
It's sort of non-compliant with Moodle's standards & conventions too. 

The other issue this would cause if the plugin is deleted, Moodle would normally clean up any settings that were associated with the plugin from the database etc, and is uses the plugin component name to hint this.

So it's not going to clear up any settings as the plugin's name is actually "plagiarism_turnitin" not "plagiarism" (as defined in the version.php file).

**Comment by danmarsden** [comment]
This dates back to when I first wrote some of this and it's a mistake I copy pasted into a few other of the plagiarism plugins I've worked on too! - one of the issues is this line in core which I wish I wrote differently when I initially wrote the Plagiarism API which looks for 
get_config('plagiarism', $plugin."_use")

https://github.com/moodle/moodle/blob/master/lib/plagiarismlib.php#L177

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
