### ISSUE TITLE
Students cannot open similarity reports in Group submissions if they are not the submitter

### ISSUE THREAD

**Issue by thepurpleblob** [turnitin/moodle-plagiarism_turnitin#481]
To reproduce...

* Create a Moodle assignment and set up Group submission mode
* Create a Moodle group of at least two users in the course
* Log in as one of the users and submit something to the Assignment
* Wait for the similarity score to return - note that the submission and the score will be (correctly) exactly the same for both users as this is a Group submission
* Log in as the *other* user in the group. The one who did not make the submission
* Attempt to open the similarity report. The score/link does not do anything. 

Analysis...

In order for the link to 'work' it needs to have a CSS class pp_origreport_open. This class is missing from the non-submitter's score. 

This code seems to be the problem (lib.php line 947)

```
// This class is applied so that only the user who submitted or a tutor can open the DV.
$useropenclass = ($USER->id == $linkarray["userid"] || $istutor) ? 'pp_origreport_open' : '';
```

The class is not applied because this is not the person that submitted the file - even though they should be able to see it as the group submitter.

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
