### ISSUE TITLE
Course id to turnitin id break

### ISSUE THREAD

**Issue by bradnielsen2981** [turnitin/moodle-plagiarism_turnitin#504]
Ok so, if for whatever reason, the owner destroys their moodle pp turnitin class using the TurnItIn website, then the moodle course site can no longer submit papers using the plugin. 

It needs to be more graceful, if no turnitin code exists, and the turnitin plugin is enabled, a new turnitin submission code needs to be generated, and the database record needs to be fixed.

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
