### ISSUE TITLE
Turnitin SDK Exception: responsexmlerror - XML Response could not be parsed

### ISSUE THREAD

**Issue by lucaboesch** [turnitin/moodle-plagiarism_turnitin#539]
According to https://moodle.org/mod/forum/discuss.php?d=406687 there is an issue with an error message

Turnitin SDK Exception: responsexmlerror - XML Response could not be parsed

and not verified submissions.

We do suffer from this issue, too.

Thanks for enquiring. Note I don't retain raising PHP to 7.4.9 as proposed in that forum thread as a viable solution.

Best,
Luca

**Comment by deraadt** [comment]
We are experiencing this issue also. It seems to occur when filenames or student names include certain characters, such as apostrophes or non-latin characters (eg ä).

Our setup is as follows.
- Moodle 3.8.3
- PHP 7.2.26
- IIS 10.0 (under Windows, of course)
- SQL Server DB

**Comment by deraadt** [comment]
With a lot of effort, we managed to upgrade PHP. We were still seeing the issue on PHP 7.3.x (although not on our test Linux instance). When we upgraded to 7.4.10, this issue went away. There doesn't seem to have been many changes in mbstring since 7.3.x, so it must be something else, possibly linked to OS. We are now seeing a deprecation warning that is not stopping the code from running.

**Comment by dmitriim** [comment]
One of our clients is affected as well. As official Ubuntu distribution includes just php7.4.3, would it be possible to implement a workaround to avoid a hassle upgrading php? 
We are happy to help if can get more details about why it's failing.

**Comment by jmcgettrick** [comment]
I suspect this is the bug in PHP/cURL is the issue: https://bugs.php.net/bug.php?id=79013

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
