### ISSUE TITLE
Slow queries in two lib functions on large data sets

### ISSUE THREAD

**Issue by vsotirasqmplus** [turnitin/moodle-plagiarism_turnitin#551]
Tue, 29 Sep 2020, 9:43 PM

SELECT pathnamehash FROM mdl_files WHERE component = 'assignsubmission_file' AND itemid = '1505368' AND source IS NOT null ORDER BY id DESC
lib.php private function update_grade($cm, $submission, $userid)
public function clean_old_turnitin_submissions($cm, $userid, $itemid, $submissiontype, $identifier)

both above functions include a query which under MySQL 5.7 run for more than 40 seconds each time reaching to 70 seconds many times. Both can be found as they include the term :

"AND source IS NOT null".

Explain output
1 SIMPLE mdl_files ref mdl_file_comfilconite_ix mdl_file_comfilconite_ix 302 const 1063994 Using index condition; Using where; Using filesort

I forgot to add $plugin->version = 2019121701;
commit 74f979a9

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
