### ISSUE TITLE
When a student removes their submission, the turnitin submission persists in Feedback Studio

### ISSUE THREAD

**Issue by DavidPoll** [turnitin/moodle-plagiarism_turnitin#569]
Moodle version 3.8.6
Plagiarism plugin 3.5+ 2020113001

On an assignment with the plagiarism plugin enabled, if a student removes their submission, the file upload is removed (see Capture A). 

Note the submission status is incorrect - but that is a known moodle bug (https://tracker.moodle.org/browse/MDL-66203) for them to fix.

So the file is removed and we cannot see the file in the submissions list (Capture A). 

However, when a teacher does marking in TurnitIn Feedback Studio, they can see and navigate t) the TurnitIn version of the submission that has been removed (see captures B and C).

This is worrying as staff might not see that the submission has been removed.

![Capture A](https://user-images.githubusercontent.com/77727993/105168398-fea91e80-5b11-11eb-971d-c28d24135a59.png)
![Capture B](https://user-images.githubusercontent.com/77727993/105168401-ff41b500-5b11-11eb-9579-1bfff1b0b4aa.png)
![Capture C](https://user-images.githubusercontent.com/77727993/105168402-ffda4b80-5b11-11eb-87b0-eb547d07cfeb.png)

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
