### ISSUE TITLE
Deprecated functions on JQuery 3.5+

### ISSUE THREAD

**Issue by hugoacfs** [turnitin/moodle-plagiarism_turnitin#578]
**Moodle security announcement**: https://moodle.org/mod/forum/discuss.php?d=419655

The new JQuery deprecates functions like `trim()` found in [/jquery/turnitin_settings.js](https://github.com/turnitin/moodle-plagiarism_turnitin/blob/master/jquery/turnitin_settings.js)

Other deprecated syntax includes `:first` found in [/jquery/jquery.dataTables.columnFilter.js](https://github.com/turnitin/moodle-plagiarism_turnitin/blob/master/jquery/jquery.dataTables.columnFilter.js)

There might be other deprecated functions, useful links: 
https://api.jquery.com/category/deprecated/deprecated-3.4/
https://api.jquery.com/category/deprecated/deprecated-3.5/

**Comment by jmcgettrick** [comment]
Thanks @hugoacfs

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
