### ISSUE TITLE
"Force" upload of submissions

### ISSUE THREAD

**Issue by mhughes2k** [turnitin/moodle-plagiarism_turnitin#583]
It appears that uploads to TII are only triggered by the student uploading the file.

We have sometimes had scenarios where the Plugin has been enabled after *some* students have already uploaded their files.
It would be good if there was a mechanism that we could get these submissions to be uploaded that didn't require any actions that changed timestamps, as using the Edit Submission option will obviously do this, and potentially turn an on-time submission in to late one (also we don't allow general staff to Edit Student Submissions because of the agreement between the student and TII to upload their work).

In an ideal world being to select a student submission (or submissions) and use the grading actions menu would be really *nice*: 

![image](https://user-images.githubusercontent.com/694841/115880854-152d8180-a443-11eb-9759-f281cbaa8c3b.png)

But this seems to only be extendable by assignfeedback plugins, so would require a fake feedbackplugin to just do this.

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
