### ISSUE TITLE
Turnitin plagiarism plugin displays student identities for blind marked assignment

### ISSUE THREAD

**Issue by mjr66** [turnitin/moodle-plagiarism_turnitin#7]
We have a number of blind-marked assignments set up on our Moodle site, and have enabled the Turnitin plagiarism plugin to allow our tutors to use Turnitin/GradeMark when marking the students work. However, when they click through to GradeMark, there are three places where the student identity is revealed to the tutor, even though they should be anonymous, and are only shown as "participant xxxxx" in Moodle -

1) At the top of the GradeMark screen, under the title of the submitted file
2) In the Submission Info tool (at the bottom left of the screen)
3) In the filename of a downloaded file

Screenshots attached...
![image1](https://cloud.githubusercontent.com/assets/15090612/10430307/5dafc214-70f6-11e5-985b-c57e79630a02.png)
![image2](https://cloud.githubusercontent.com/assets/15090612/10430306/5daf3bd2-70f6-11e5-9b68-2baaeb0d6eab.png)

Are we doing something wrong, or is this a bug? Many thanks!

**Comment by mjr66** [comment]
Sorry, I should have added - we are using Moodle 2.9.1+ (Build: 20150813) and Turnitin plugins version 2015040107

**Comment by cwestgarth** [comment]
Hello @mjr66, 
Can you please drop me an email with your contact details and your institution. My email address is cwestgarth@turnitin.com. 

Thank you 
Caroline Westgarth

**Comment by esslw** [comment]
Hi Caroline
As you know, both Bath and Strathclyde have also raised this issue at:
* https://github.com/jmcgettrick/MoodleDirectV2/issues/160
(subsequently moved to https://github.com/turnitin/moodle-plagiarism_turnitin/issues/3)

...alongside a related issue regarding the plugin returning Grademark grades back to the Moodle gradebook:
*  https://github.com/jmcgettrick/moodle-plagiarism_turnitin/issues/27

Since these original items have now been closed, it would be helpful if any updates were posted here so that all those who have raised the issues can be kept in the loop.

Thanks

**Comment by jmcgettrick** [comment]
We have reworked Blind and Anonymous marking in today's release (2015040111). The anonymous marking setting has been removed and the plugin now uses Moodle's blind marking setting to set whether the assignment is anonymous in Turnitin.
